### ISSUE TITLE
in silico DATA

### ISSUE THREAD

**Issue by ReDoDx09** [RI-imaging/ODTbrain#14]
Good morning all 
So, I would like to do some tomography reconstruction simulation but before that, I have to create phantom object and collected projections using meep package, I saw that you already did this but I didn't find it on your GitHub. please could you tell me where to find the script to generate in silico data set created with the software meep.
PS: I'm using python

**Comment by paulmueller** [comment]
You can find the files here: https://github.com/RI-imaging/ODTbrain/tree/master/misc
